name: Enviar token diario

on:
  schedule:
    - cron: '1 0 * * *' # 00:01 UTC todos los días

jobs:
  send-token:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar script
        run: node token-sender.js